name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache SBT
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache
          target
          project/target
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/build.properties', 'project/plugins.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-
          
    - name: Download and setup SBT
      run: |
        curl -L -o sbt.tgz https://github.com/sbt/sbt/releases/download/v1.10.11/sbt-1.10.11.tgz
        tar -xzf sbt.tgz
        export PATH="$PWD/sbt/bin:$PATH"
        sbt --version
        
    - name: Compile project
      run: |
        export PATH="$PWD/sbt/bin:$PATH"
        sbt compile
        
    - name: Run tests
      run: |
        export PATH="$PWD/sbt/bin:$PATH"
        sbt test
